CREATE TABLE USERS
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY(start with 1) PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL

);

CREATE TABLE USER_ROLES
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);


CREATE TABLE RESTAURANTS
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY(start with 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


CREATE TABLE DISHES
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY(start with 1) PRIMARY KEY,
    date_time   DATE DEFAULT now(),
    description VARCHAR(255)   NOT NULL,
    price       DECIMAL(10, 2) NOT NULL,
    rest_id     INTEGER        NOT NULL,
    FOREIGN KEY (rest_id) REFERENCES RESTAURANTS (id) ON DELETE CASCADE

);
CREATE INDEX dishes_rest_dish_idx ON dishes (rest_id, date_time);


CREATE TABLE voting_result
(

    id         INTEGER GENERATED BY DEFAULT AS IDENTITY(start with 1) PRIMARY KEY,
    vote_date  TIMESTAMP DEFAULT now(),
    rest_name  VARCHAR(255) NOT NULL,
    count_vote INTEGER      NOT NULL

);